version: '3.1'

services:

  #Billing databases service
  postgres_db_prod:
    container_name: postgres_prod
    image: postgres:latest
    restart: always
    networks:
      - env_prod
    ports:
      - 5432:5432
    volumes:
      - ./dbfiles:/docker-entrypoint-initdb.d
      - /var/lib/postgres_data_prod:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres

  postgres_db_prep:
    container_name: postgres_prep
    image: postgres:latest
    restart: always
    networks:
      - env_prep
    ports:
      - 4432:5432
    volumes:
      - ./dbfiles:/docker-entrypoint-initdb.d
      - /var/lib/postgres_data_prep:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres

  #adminer
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on: 
      - postgres_db_prod
      - postgres_db_prep
    networks:
      - env_prod
      - env_prep
    ports:
       - 9090:8080

  #Billing app backend service
  billingapp-back-prod:
    build:
      context: ./java
      args:
        - JAR_FILE=billing-0.0.3-SNAPSHOT.jar
    container_name: billingApp-back-prod   
    environment:
       - JAVA_OPTS=
         -Xms256M 
         -Xmx256M         
    depends_on:     
      - postgres_db_prod
    networks:
      - env_prod
    ports:
      - 8080:8080 
    
  billingapp-back-prep:
    build:
      context: ./java
      args:
        - JAR_FILE=billing-0.0.2-SNAPSHOT.jar
    container_name: billingApp-back-prep 
    environment:
       - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
    networks:
      - env_prep
    depends_on:     
      - postgres_db_prep
    ports:
      - 7080:7080 

  #Billing app frontend service
  billingapp-front-prod:
    build:
      context: ./angular 
    deploy:   
        resources:
           limits: 
              cpus: "0.15"
              memory: 250M
           reservations:
              cpus: "0.1"
              memory: 128M
    depends_on:     
      - billingapp-back-prod
    networks:
      - env_prod
    ports:
      - 81:80 

  billingapp-front-prep:
    build:
      context: ./angular 
    deploy:   
        resources:
           limits: 
              cpus: "0.15"
              memory: 250M
           reservations:
              cpus: "0.1"
              memory: 128M
    depends_on:     
      - billingapp-back-prep
    networks:
      - env_prep
    ports:
      - 82:81

networks:
  env_prod:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config: 
        -
          subnet: 177.16.232.0/24
          gateway: 177.16.232.1
        -
          subnet: "2001:3974:3979::/64"
          gateway: "2001:3974:3979::1"

  env_prep:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config: 
        -
          subnet: 177.16.235.0/24
          gateway: 177.16.235.1
        -
          subnet: "2001:3984:3989::/64"
          gateway: "2001:3984:3989::1"